---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /  # Переписывает путь запроса (при необходимости)
    kubernetes.io/ingress.class: nginx  # Указывает, что используется Ingress-nginx
spec:
  rules:
    - host: {{ .Values.ingress.address }}
      http:
        paths:
          - path: /   # Определяет путь, который будет направлен на ваш сервис
            pathType: Prefix
            backend:
              service:
                name: {{ .Chart.Name }}  # Имя вашего сервиса
                port:
                  number: {{ .Values.service.port }}  # Порт, на который будет направлен запрос
